### ISSUE TITLE
Missing ICSE paper

### ISSUE THREAD

**Issue by klerisson** [aserg-ufmg/CSIndex#14]
It's an ICSE full technical paper with 9 pages, but I think it deserves to be indexed.

R. Prikladnicki and E. Carmel, "Is time-zone proximity an advantage for software development? The case of the Brazilian IT industry," 2013 35th International Conference on Software Engineering (ICSE), San Francisco, CA, 2013, pp. 973-981.
doi: 10.1109/ICSE.2013.6606647

**Comment by mtov** [comment]
But it seems to be ICSE-SEIP:

https://www.computer.org/csdl/proceedings/icse/2013/3073/00/06606542.pdf

**Comment by klerisson** [comment]
hum... my bad.
I only looked at DBLP bibtex and it does not have any difference like newest SEIP track bibtex.
