### ISSUE TITLE
Artigos não constam no CSIndex

### ISSUE THREAD

**Issue by denilsonalvespereira** [aserg-ufmg/CSIndex#15]
Tenho dois artigos na JCDL, em 2014 e 2017, e eles não aparecem no CSIndex.
Nome: Denilson Alves Pereira
Departamento: Ciência da Computação, UFLA
Artigos:
PEREIRA, Denilson Alves; DA SILVA, EDUARDO EMANUEL BRAGA ; Esmin, Ahmed A. A. . Disambiguating publication venue titles using association rules. In: 2014 IEEE/ACM Joint Conference on Digital Libraries (JCDL), 2014, London. IEEE/ACM Joint Conference on Digital Libraries. p. 77-86.

CASTRO, EDUARDO P. S. ; CHAKRAVARTY, SAURABH ; WILLIAMSON, ERIC ; PEREIRA, Denilson Alves ; FOX, EDWARD A. . Classifying Short Unstructured Data Using the Apache Spark Platform. In: 2017 ACM/IEEE Joint Conference on Digital Libraries (JCDL), 2017, Toronto. 2017 ACM/IEEE Joint Conference on Digital Libraries (JCDL), 2017.

Favor verificar.

**Comment by mtov** [comment]
Olá Denilson, papers indexados; obrigado por nos avisar.
