### ISSUE TITLE
Paper not indexed

### ISSUE THREAD

**Issue by rsmbarros** [aserg-ufmg/CSIndex#16]
Roberto Souto Maior de Barros
Centro de Informática, Universidade Federal de Pernambuco - CIN-UFPE

Title - Speeding Up Recovery from Concept Drifts. 
Conference - ECML/PKDD (3) 2014: 
Springer volume 8726 of LNCS, pages 179-194
Authors - Silas Garrido Teixeira de Carvalho Santos, Paulo Mauricio Gonçalves Júnior, Geyson Daniel dos Santos Silva, Roberto Souto Maior de Barros:

**Comment by mtov** [comment]
Obrigado pela lembrança do paper; já foi adicionado.
