### ISSUE TITLE
shouldn't ISSTA be considered "near the top"?

### ISSUE THREAD

**Issue by damorim** [aserg-ufmg/CSIndex#17]
I am assuming the reference for this classification is csrankings.org.

PS. I was not sure if this should be in English or Portuguese.

**Comment by mtov** [comment]
Oi Marcelo,

Tanto faz, inglês ou português ...  mas eu vou responder em português mesmo ....

Não usamos o CSRankings, porque eles usam uma licença que impede qualquer reúso de dados do sistema. Não podemos, por exemplo, reusar no CSIndex, mesmo que manualmente ou indiretamente, a classificação de top-conferences deles.

Por isso, decidimos fazer uma classificação própria de top-conferences, para o CSIndex, baseada nas métricas que coletamos: submitted, accepted e h5-index.

Analisando essas métricas, chegamos às seguintes conclusões na área de Engenharia de Software:

* Existem duas conferências que se destacam principalmente em h5-index: ICSE (h5-index= 68) e FSE (h5-index= 43); que, logo foram classificadas como top.

* Depois, ASE fica perto, principalmente em submitted (~300 papers) e acceptance (˜20%); logo, ela foi classificada como near-the-top.

Depois, não tem nenhuma conferência perto de ASE, principalmente em submitted; as demais conferências, principalmente MSR e ISSTA tem menos da metade de submissões  (~120 papers); e sobre ISSTA especificamente o seu h5-index (31) é menor que o da MSR (39).  Logo, decidimos "interromper" a classificação de near-the-top após classificar ASE.

Tem ainda um segundo componente importante: via de regra, tentamos classificar como top e near-the-top conferências cobrindo um amplo conjunto de tópicos de pesquisa em uma área. Logo, ASE neste critério é também diferente de ISSTA.
