### ISSUE TITLE
Novo departamento: UFPA

### ISSUE THREAD

**Issue by gustavopinto** [aserg-ufmg/CSIndex#24]
Pedido para criação de departamento da UFPA. Professores:

Eduardo Cerqueira
Denis Rosario
Aldebaro Klautau
Cleidson Souza
Gustavo Pinto
Sandro Ronaldo Bezerra Oliveira
Eloi Luiz Favero
Ronnie Alves
Roberto Celio Limao de Oliveira
Reginaldo Santos
Lidio Mauro Lima de Campos
Claudomiro Sales
Viviane Santos (*nåo tem entrada no csindex, artigo: https://link.springer.com/article/10.1007%2Fs10664-014-9307-y)

**Comment by mtov** [comment]
Feito!

https://csindexbr.org/depts.html?d=ufpa
